sudo: false

sudo: false

#!/Users/brian/bin/perls/perl5.22.0
use v5.10;

my $data = do { local( $/ ); <DATA> };

$data =~ s/\t/    /gm;
$data =~ s/\h+-\h"5\.20"\n\h*\n/    - "5.20"\n    - "5.22"\n\n/;
$data =~ s/\s+\z//gm;

my $top =<<"HERE";
sudo: false

HERE

say $top . $data;

__END__
language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init --auto

install:
    - cpanm --quiet --installdeps --notest .
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - cover -delete && cover -test

after_success:
    - cover -report coveralls